ansh_dbt_youtube:
  outputs:
    dev:
      catalog: dbt_tutorial_dev
      host: dbc-ce9fa16f-a99d.cloud.databricks.com
      http_path: /sql/1.0/warehouses/3909992a1da1631e
      schema: default
      threads: 1
      token: "{{ env_var('DATABRICKS_TOKEN') }}"
      type: databricks
    prod:
      catalog: dbt_tutorial_prod
      host: dbc-ce9fa16f-a99d.cloud.databricks.com
      http_path: /sql/1.0/warehouses/3909992a1da1631e
      schema: default
      threads: 1
      token: "{{ env_var('DATABRICKS_TOKEN') }}"
      type: databricks
  target: dev
